#spring:
#  datasource:
#    driver-class-name: org.sqlite.JDBC
#    url: jdbc:sqlite:test.db

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:address.db



server:
  port: 8080

mybatis-plus:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.xjtlu.monitor.pojo

